# Generated by Django 5.0.6 on 2025-04-24 21:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crud_Opt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
